import { Inter } from 'next/font/google';
import { UserProvider } from '@/context';
import './globals.css';

import Navbar from '@/components/Navbar';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Sod',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`pb-10 ${inter.className}`}>
        {/* <script src="https://js.stripe.com/v3/"></script> */}
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
